baseurl = "https://rmn-web.netlify.com"
languageCode = "ja-jp"
title = "まつゆき/rmn."

[[menu.main]]
  name = "プロフィール"
  url = "/page/profile"
  
[[menu.main]]
  name = "復元サイト"
  url = "http://info.wwawing.com/restore/"

[[menu.main]]
  name = "更新履歴"
  url = "/page/history"

[[menu.main]]
  name = "ポートフォリオ"
  url = "http://portfolio.rmn-web.net/"

[[menu.main]]
  name = "WWA Wing"
  url = "http://wwawing.com/"

[params]
copyright = "2003-2019 Matsuyuki ( CC BY 4.0 License )"
licensePage = "/page/license"
