baseurl = "https://rmn-web.net/"
languageCode = "ja-jp"
title = "【更新終了】まつゆき ＜旧ブログ＞"

[[menu.main]]
  name = "更新履歴"
  url = "/page/history"

[[menu.main]]
  name = "サイト本体へ戻る"
  url = "https://matsuyuki.dev"

[params]
copyright = "2003-2019 Matsuyuki ( CC BY 4.0 License )"
licensePage = "/page/license"
